### ISSUE TITLE
Error when using from release page

### ISSUE THREAD

**Issue by mosheDO** [allthingsida/qscripts#4]
Hi

I get an Error when using from the release page

```
(plugins\qscripts64.dll) error: The specified procedure could not be found.
plugins\qscripts64.dll: can't load file
```
are you familiar with this error?

**Comment by 0xeb** [comment]
What’s your IDA version?

**Comment by mosheDO** [comment]
Hi

sorry for not mention but 7.7

**Comment by 0xeb** [comment]
Try to grab an older release then. Or build from sources.

**Comment by mosheDO** [comment]
It can be related to the python version?

Cause it seems like other plugins doesn't work as well

**Comment by mosheDO** [comment]
Wow your YT video on cmake helped me so much and building from source worked 
I really appreciate your work

You can close it
