### ISSUE TITLE
Place it into my ida 7.6SP1 but it doesn't work 

### ISSUE THREAD

**Issue by breaking153** [allthingsida/qscripts#5]
![image](https://github.com/0xeb/ida-qscripts/assets/49428332/b66cfc42-d318-41e7-8534-de5399e076bb)

but my ida8.3 can normally load the plugin.

**Comment by breaking153** [comment]
does it need more dependency?

**Comment by 0xeb** [comment]
Find an earlier version of QScripts for older IDA.

**Comment by breaking153** [comment]
Thanks. It works!
