### ISSUE TITLE
support for 9.0?

### ISSUE THREAD

**Issue by 0xGotcha** [allthingsida/qscripts#8]
support for 9.0?

**Comment by 0xeb** [comment]
Yes, IDA 9.0 is in beta right now.

**Comment by 0xeb** [comment]
Download Windows binary from here: https://github.com/allthingsida/qscripts/releases/tag/v1.2.5.1_90

**Comment by alexander-pick** [comment]
I tried to build it with IDA 9.0 SDK but it seems to have a bad library reference:

```
make[2]: *** No rule to make target '<REDACTED>/idasdk90//lib/x64_linux_gcc_64/libida64.so', needed by '/<REDACTED>/ida-pro-9.0/ida/plugins/qscripts.so'.  Stop.
```

The file name is libida.so now.

Edit:
It's related to ida-cmake, PR here: https://github.com/allthingsida/ida-cmake/pull/10
