### ISSUE TITLE
Not work in ida9.0 release.

### ISSUE THREAD

**Issue by Dormzz** [allthingsida/qscripts#9]
here is torrent! please support!

https://bbs.kanxue.com/attach-download-345700-75213b9cd82e436ad95a5996d2a4992f@ehhWhrsbmJ5PKhJUeGPChA_3D_3D.htm

**Comment by 0xeb** [comment]
Download the Windows binary from here: Download Windows binary from here: https://github.com/allthingsida/qscripts/releases/tag/v1.2.5.1_90

Let me know.

**Comment by Dormzz** [comment]
I use mac x64 ida pro.

**Comment by 0xeb** [comment]
Good. Feel free to build it yourself. All the instructions are up there.
